
GET http://localhost:3001/api/arts

###
POST http://localhost:3001/api/arts 
Content-Type: application/json

{
    "piece": "Waves",
    "description": "fluid blues",
    "userId": "60c247cde9c60241b6cab31e"
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "trungy",
    "password": "awesome1"
}
