
GET http://localhost:3001/api/arts

###
POST http://localhost:3001/api/arts 
Content-Type: application/json

{
    "piece": "Waves",
    "description": "fluid blues",

}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "trungy",
    "password": "awesome1"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "trungy",
    "password": "awesome1"
}

###
POST http://localhost:3001/api/capsules
Content-Type: application/json

{
    "title": "May 2021",
    "description": "farewell spring"
}
